### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by jdantonio** [monterail/multiblock#2]
Is this gem still being maintained? It seems like an excellent tool but it hasn't been updated in a while and the build is failing. I can't imagine a need to add features, but CI is still running against old, unsupported versions of Ruby and not the latest releases.

**Comment by szajbus** [comment]
@jdantonio Thanks for pointing that out. I fixed the build and added testing against 2.1 and 2.2 lines. 

It's green again :green_heart: :build:
